 <?php
 // module/Album/view/album/album/index.phtml:

 $title = 'My albums';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php foreach ($scenes as $scene) : ?>
<?php echo $this->escapeHtml($scene->title);?>
<?php echo $this->escapeHtml($scene->eid);?>
<a href="<?php echo $this->url('scene',
	array('action'=>'edit', 'id' => $scene->id));?>">Edit</a>
<a href="<?php echo $this->url('scene',
	array('action'=>'delete', 'id' => $scene->id));?>">Delete</a>	
	<br/>
 <?php endforeach; ?>
